---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/1/posts/1/comments":
    post:
      summary: Creates a comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: comment created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                user_id:
                  type: integer
                author_id:
                  type: integer
                post_id:
                  type: integer
              required:
              - user_id
              - post_id
  "/users/1/posts.json":
    get:
      summary: Retrieves all posts
      tags:
      - Posts
      responses:
        '200':
          description: posts retrieved
  "/users/1/posts/24.json":
    get:
      summary: Show comments for a post
      tags:
      - Show Comment
      responses:
        '200':
          description: comment retrieved
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
